// app/api/analytics/route.ts
import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export async function GET(req: Request) {
  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    
    if (authError || !user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { data: config } = await supabase
      .from('bot_config')
      .select('space_id')
      .eq('user_id', user.id)
      .maybeSingle();

    if (!config?.space_id) {
      return NextResponse.json({ feedbacks: [], volumeData: [], aiInsights: null });
    }

    // 1. Fetch raw feedback data
    const { data: feedbacks, error } = await supabase
      .from('chat_feedback')
      .select('*')
      .eq('space_id', config.space_id)
      .order('created_at', { ascending: false });

    if (error) throw error;

    // 2. Build 30-day volume data for charts
    const volumeMap: Record<string, number> = {};
    const now = new Date();
    
    for (let i = 29; i >= 0; i--) {
      const d = new Date(now);
      d.setDate(d.getDate() - i);
      const dateStr = d.toISOString().split('T')[0];
      volumeMap[dateStr] = 0;
    }

    if (feedbacks) {
      feedbacks.forEach(f => {
        const dateStr = new Date(f.created_at).toISOString().split('T')[0];
        if (volumeMap[dateStr] !== undefined) {
          volumeMap[dateStr]++;
        }
      });
    }

    const volumeData = Object.keys(volumeMap).map(date => {
      const d = new Date(date);
      return {
        date: d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
        interactions: volumeMap[date]
      };
    });

    // 3. Fetch the most recent AI insight generated by the cron job
    const { data: latestInsight } = await supabase
      .from('space_insights')
      .select('insights')
      .eq('space_id', config.space_id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    return NextResponse.json({ 
      feedbacks: feedbacks || [], 
      volumeData, 
      aiInsights: latestInsight?.insights || null 
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
